services:

  nginx:
    image: nginx:1.27.4-alpine3.21
    container_name: nginx_proxy
    ports:
      - "80:80"   
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./project/src/main/webapp/setup/index.html:/usr/share/nginx/html/index.html:ro
      - ./project/src/main/webapp:/usr/share/nginx/html/webapp:ro
    depends_on:
      - lavagna
      - mysql
    networks:
      - lavagna-network
      
  lavagna:
    build: .
    container_name: lavagna_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_DIALECT: "MYSQL"
      DB_URL: "jdbc:mysql://mysql:3306/lavagna?autoReconnect=true&useSSL=false"
      DB_USER: "lavagna"
      DB_PASS: lavagna_pass
      SPRING_PROFILE: "dev"
    networks:
      - lavagna-network

  mysql:
    image: mysql:5.7
    container_name: lavagna_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: lavagna
      MYSQL_USER: lavagna
      MYSQL_PASSWORD: lavagna_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lavagna-network

networks:
  lavagna-network:
volumes:
  mysql_data: